"""
knowledge_base.py
-----------------
All Clarkson University knowledge documents for myAdvisr RAG.
Each document is a dict: {"id": str, "text": str, "metadata": dict}

Categories:
  - courses       : individual course entries (code, name, credits, prereqs, description)
  - programs      : degree requirements per major
  - policies      : academic policies, deadlines, rules
  - resources     : campus offices, contacts, hours
  - careers       : career paths, employer data, salary info
"""

DOCUMENTS = [

    # ══════════════════════════════════════════════════════════
    #  COMPUTER SCIENCE COURSES
    # ══════════════════════════════════════════════════════════
    {"id": "cs141", "text": "CS 141 Introduction to Computer Science I. Credits: 4. Prerequisites: none. Description: Fundamental programming concepts using Python. Topics include variables, loops, functions, recursion, and basic data structures. Required for all CS and Data Science majors. Offered every fall and spring.", "metadata": {"category": "course", "dept": "CS", "level": "100"}},
    {"id": "cs142", "text": "CS 142 Introduction to Computer Science II. Credits: 3. Prerequisites: CS 141. Description: Object-oriented programming, inheritance, polymorphism, exception handling, file I/O, and introduction to algorithms. Required for CS majors.", "metadata": {"category": "course", "dept": "CS", "level": "100"}},
    {"id": "cs242", "text": "CS 242 Advanced Programming. Credits: 3. Prerequisites: CS 142. Description: Advanced programming techniques including data abstraction, generic programming, GUI development, and software engineering principles.", "metadata": {"category": "course", "dept": "CS", "level": "200"}},
    {"id": "cs344", "text": "CS 344 Algorithms and Data Structures. Credits: 3. Prerequisites: CS 142, MA 211. Description: Design and analysis of algorithms. Topics include sorting, searching, graph algorithms, dynamic programming, greedy algorithms, and computational complexity. Required for CS and Data Science majors.", "metadata": {"category": "course", "dept": "CS", "level": "300"}},
    {"id": "cs348", "text": "CS 348 Computer Organization. Credits: 3. Prerequisites: CS 242. Description: Digital logic, computer arithmetic, memory hierarchy, instruction set architectures, pipelining, and input/output systems.", "metadata": {"category": "course", "dept": "CS", "level": "300"}},
    {"id": "cs443", "text": "CS 443 Database Systems. Credits: 3. Prerequisites: CS 344. Description: Relational database design, SQL, normalization, transactions, concurrency control, and NoSQL databases. Highly recommended for Data Science and Software Engineering tracks.", "metadata": {"category": "course", "dept": "CS", "level": "400"}},
    {"id": "cs444", "text": "CS 444 Operating Systems. Credits: 3. Prerequisites: CS 348. Description: Processes, threads, synchronization, deadlocks, memory management, file systems, and distributed systems fundamentals.", "metadata": {"category": "course", "dept": "CS", "level": "400"}},
    {"id": "cs447", "text": "CS 447 Machine Learning. Credits: 3. Prerequisites: CS 344, STAT 282 or STAT 383. Description: Supervised and unsupervised learning, regression, classification, neural networks, support vector machines, and model evaluation. Highly recommended for Data Science and AI career tracks.", "metadata": {"category": "course", "dept": "CS", "level": "400"}},
    {"id": "cs451", "text": "CS 451 Computer Networks. Credits: 3. Prerequisites: CS 444. Description: Network architecture, protocols (TCP/IP, HTTP, DNS), socket programming, security fundamentals, and wireless networks.", "metadata": {"category": "course", "dept": "CS", "level": "400"}},
    {"id": "cs499", "text": "CS 499 Professional Experience. Credits: 3. Prerequisites: junior standing, 60+ credits completed. Description: Internship, co-op, or directed research related to the student's professional goals. Required for graduation in all CS and Data Science programs. Must be approved by the department.", "metadata": {"category": "course", "dept": "CS", "level": "400"}},
    {"id": "cs541", "text": "CS 541 Computer Algorithms (Graduate). Credits: 3. Prerequisites: Graduate standing or permission. Description: Advanced algorithm design and analysis. Required foundation course for the MS in Computer Science. Must be taken in first semester.", "metadata": {"category": "course", "dept": "CS", "level": "500"}},
    {"id": "cs547", "text": "CS 547 Machine Learning I (Graduate). Credits: 3. Prerequisites: CS 541 or permission. Description: Statistical learning theory, kernel methods, deep learning fundamentals, reinforcement learning basics. Part of the AI/ML graduate track.", "metadata": {"category": "course", "dept": "CS", "level": "500"}},

    # ══════════════════════════════════════════════════════════
    #  MATHEMATICS COURSES
    # ══════════════════════════════════════════════════════════
    {"id": "ma131", "text": "MA 131 Calculus I. Credits: 3. Prerequisites: precalculus or placement. Description: Limits, derivatives, applications of differentiation, introduction to integration. Required for all engineering, CS, math, and science majors. Offered every semester.", "metadata": {"category": "course", "dept": "MA", "level": "100"}},
    {"id": "ma132", "text": "MA 132 Calculus II. Credits: 3. Prerequisites: MA 131. Description: Integration techniques, sequences and series, polar coordinates, parametric equations. Required for engineering, CS, and science majors.", "metadata": {"category": "course", "dept": "MA", "level": "100"}},
    {"id": "ma211", "text": "MA 211 Foundations of Mathematics. Credits: 3. Prerequisites: MA 131. Description: Logic, set theory, proof techniques, relations, functions, and combinatorics. Required for CS majors. Develops mathematical maturity for upper-division coursework.", "metadata": {"category": "course", "dept": "MA", "level": "200"}},
    {"id": "ma231", "text": "MA 231 Differential Equations. Credits: 3. Prerequisites: MA 132. Description: First and higher-order ODEs, systems of equations, Laplace transforms, and introduction to partial differential equations. Required for all engineering majors.", "metadata": {"category": "course", "dept": "MA", "level": "200"}},
    {"id": "ma232", "text": "MA 232 Calculus III. Credits: 3. Prerequisites: MA 132. Description: Multivariable calculus, partial derivatives, multiple integrals, line and surface integrals, vector calculus (Green's, Stokes', and Divergence theorems).", "metadata": {"category": "course", "dept": "MA", "level": "200"}},
    {"id": "ma335", "text": "MA 335 Linear Algebra. Credits: 3. Prerequisites: MA 132. Description: Vectors, matrices, linear transformations, eigenvalues and eigenvectors, orthogonality, and applications. Recommended for CS and Data Science majors interested in ML and AI.", "metadata": {"category": "course", "dept": "MA", "level": "300"}},

    # ══════════════════════════════════════════════════════════
    #  STATISTICS COURSES
    # ══════════════════════════════════════════════════════════
    {"id": "stat282", "text": "STAT 282 Probability and Statistics for Engineers and Scientists. Credits: 3. Prerequisites: MA 132. Description: Probability theory, random variables, distributions, hypothesis testing, regression, and ANOVA. Required for Data Science, CS, and all engineering majors. This course is the prerequisite for CS 447 Machine Learning.", "metadata": {"category": "course", "dept": "STAT", "level": "200"}},
    {"id": "stat383", "text": "STAT 383 Applied Statistics. Credits: 3. Prerequisites: STAT 282. Description: Multiple regression, experimental design, time series analysis, nonparametric methods, and statistical computing with R. Core course for Data Science majors.", "metadata": {"category": "course", "dept": "STAT", "level": "300"}},

    # ══════════════════════════════════════════════════════════
    #  ENGINEERING COURSES
    # ══════════════════════════════════════════════════════════
    {"id": "me221", "text": "ME 221 Statics. Credits: 3. Prerequisites: MA 131, PH 131. Description: Equilibrium of particles and rigid bodies, distributed forces, centroids, moments of inertia, friction, and analysis of trusses and frames. Required for all Mechanical and Aerospace Engineering majors.", "metadata": {"category": "course", "dept": "ME", "level": "200"}},
    {"id": "me323", "text": "ME 323 Thermodynamics I. Credits: 3. Prerequisites: MA 132, PH 131. Description: First and second laws of thermodynamics, thermodynamic properties, power and refrigeration cycles. Required for Mechanical and Aerospace Engineering.", "metadata": {"category": "course", "dept": "ME", "level": "300"}},
    {"id": "che211", "text": "CHE 211 Material and Energy Balances. Credits: 3. Prerequisites: CM 131, MA 131. Description: Systematic application of conservation laws to chemical processes. Includes steady-state and unsteady-state balances with and without chemical reaction. Required first course for Chemical Engineering majors.", "metadata": {"category": "course", "dept": "CHE", "level": "200"}},
    {"id": "ce322", "text": "CE 322 Structural Analysis. Credits: 3. Prerequisites: CE 221 or ES 220. Description: Analysis of statically determinate and indeterminate structures including beams, frames, and trusses. Required for Civil Engineering majors.", "metadata": {"category": "course", "dept": "CE", "level": "300"}},

    # ══════════════════════════════════════════════════════════
    #  BUSINESS COURSES
    # ══════════════════════════════════════════════════════════
    {"id": "sb113", "text": "SB 113 Entrepreneurship and Business Innovation. Credits: 3. Prerequisites: none. Description: Introduction to entrepreneurship, business model development, innovation processes, and lean startup methodology. REQUIRED for ALL undergraduate students in the Reh School of Business regardless of major. Typically taken in freshman year.", "metadata": {"category": "course", "dept": "SB", "level": "100"}},
    {"id": "ac201", "text": "AC 201 Financial Accounting. Credits: 3. Prerequisites: none. Description: Principles of financial accounting, financial statements, recording transactions, assets, liabilities, equity, and cash flows. Required for all Reh School undergraduate programs.", "metadata": {"category": "course", "dept": "AC", "level": "200"}},
    {"id": "fi301", "text": "FI 301 Financial Management. Credits: 3. Prerequisites: AC 201, EC 200. Description: Time value of money, capital budgeting, risk and return, cost of capital, capital structure, and dividend policy. Required for Business Administration and Financial Information & Analysis majors.", "metadata": {"category": "course", "dept": "FI", "level": "300"}},
    {"id": "mk301", "text": "MK 301 Marketing Management. Credits: 3. Prerequisites: SB 113 or AC 201. Description: Marketing strategy, consumer behavior, market segmentation, pricing, promotion, and distribution. Core course for Business Administration majors.", "metadata": {"category": "course", "dept": "MK", "level": "300"}},

    # ══════════════════════════════════════════════════════════
    #  CLARKSON COMMON EXPERIENCE
    # ══════════════════════════════════════════════════════════
    {"id": "univ190", "text": "UNIV 190 The Clarkson Seminar. Credits: 3. Prerequisites: first-year standing. Description: Interdisciplinary seminar exploring connections between technology, society, and culture. Required for ALL Clarkson undergraduate students regardless of major. Typically taken in the fall semester of the first year. Offered every fall.", "metadata": {"category": "course", "dept": "UNIV", "level": "100"}},
    {"id": "fy100", "text": "FY100 First-Year Seminar. Credits: 1. Prerequisites: first-year standing. Description: Orientation to university life, academic skills, campus resources, and community engagement. Required for all first-year undergraduate students. Taken alongside UNIV 190 in the first fall semester.", "metadata": {"category": "course", "dept": "FY", "level": "100"}},

    # ══════════════════════════════════════════════════════════
    #  UNDERGRADUATE DEGREE REQUIREMENTS
    # ══════════════════════════════════════════════════════════
    {"id": "req_cs_ug", "text": "Computer Science BS degree requirements at Clarkson University. Total credits required: 120. The CS major consists of 43 credits in computer science, 15 credits in mathematics (MA 131, 132, 211, and 2 math electives), and 12 credits in science. Students must complete CS 499 Professional Experience before graduation. Required CS courses: CS 141 (4 cr), CS 142, CS 242, CS 344, CS 348, CS 444, CS 451. Students need 30 free elective credits which can be used for a minor or second major. Average time to complete: 4 years (8 semesters).", "metadata": {"category": "program", "major": "Computer Science", "level": "undergraduate"}},
    {"id": "req_ds_ug", "text": "Data Science BS degree requirements at Clarkson University. Total credits required: 120. Core requirements include CS 141 (4 cr), CS 142, CS 344, CS 443, CS 447, MA 131, MA 132, STAT 282, STAT 383, MA 335 (Linear Algebra). Data Science is a STEM-designated program. Students must complete a 6-credit capstone project and CS 499 Professional Experience. Offered jointly by the CS and Statistics departments. Average time to complete: 4 years.", "metadata": {"category": "program", "major": "Data Science", "level": "undergraduate"}},
    {"id": "req_me_ug", "text": "Mechanical Engineering BS degree requirements at Clarkson University. Total credits required: 120. The 73 credit hours in ME include applied physics, applied mathematics, engineering science, and mechanical engineering. Required courses: MA 131, MA 132, MA 231, PH 131, PH 132, ME 170, ME 221, ME 222, ME 323, ME 332, ME 422, ME 424, ME 456, ME 457. Students must complete a Professional Experience (co-op or internship). ABET accredited. Average time: 4 years.", "metadata": {"category": "program", "major": "Mechanical Engineering", "level": "undergraduate"}},
    {"id": "req_ae_ug", "text": "Aeronautical Engineering BS degree requirements at Clarkson University. Total credits required: 120. The 87 credit hours in aerospace engineering include applied physics, applied mathematics, engineering science, and mechanical engineering. Required courses: AE 160, AE 324, AE 333, AE 421, AE 432, ME 170, ME 221, ME 323, MA 131, MA 132, MA 231, PH 131, PH 132. Must complete Professional Experience. ABET accredited. Average time: 4 years.", "metadata": {"category": "program", "major": "Aeronautical Engineering", "level": "undergraduate"}},
    {"id": "req_ce_ug", "text": "Civil Engineering BS degree requirements at Clarkson University. Total credits required: 120. Required courses include: CE 201, CE 221, CE 322, CE 331, CE 341, CE 421, CE 431, CE 451, CE 452, MA 131, MA 132, MA 231, PH 131, CM 131. Students can specialize in structural, environmental, geotechnical, or water resources engineering. ABET accredited. Must complete Professional Experience. Average time: 4 years.", "metadata": {"category": "program", "major": "Civil Engineering", "level": "undergraduate"}},
    {"id": "req_ee_ug", "text": "Electrical Engineering BS degree requirements at Clarkson University. Total credits required: 120. The EE program consists of 36 credit hours in electrical engineering and 27 credit hours of first-year engineering curriculum. Required EE courses: EE 221, EE 264, EE 321, EE 324, EE 331, EE 333, EE 341, EE 381, ES 250. Class of 2024 had 100% placement rate. ABET accredited. Must complete Professional Experience.", "metadata": {"category": "program", "major": "Electrical Engineering", "level": "undergraduate"}},
    {"id": "req_che_ug", "text": "Chemical Engineering BS degree requirements at Clarkson University. Total credits required: 120. Required courses: CHE 211, CHE 312, CHE 321, CHE 331, CHE 411, CHE 421, CHE 451, CHE 452, CM 131, CM 132, MA 131, MA 132, MA 231, PH 131, BY 141. Biomolecular Engineering concentration available. ABET accredited. Must complete Professional Experience. Average starting salary for Class of 2024: over $74,000.", "metadata": {"category": "program", "major": "Chemical Engineering", "level": "undergraduate"}},
    {"id": "req_ba_ug", "text": "Business Administration BS degree requirements at Clarkson University (Reh School of Business). Total credits required: 120. Required courses: SB 113 (required for all Reh students), AC 201, AC 202, EC 200, MG 201, MK 201, MK 301, FI 301, MG 301, IS 201, MG 401, BA 301. International experience is REQUIRED for all Reh School undergrads. Students must complete a Professional Experience. Average time: 4 years.", "metadata": {"category": "program", "major": "Business Administration", "level": "undergraduate"}},
    {"id": "req_gscm_ug", "text": "Global Supply Chain Management BS degree requirements at Clarkson University (Reh School of Business). Total credits required: 120. Required: SB 113, SCM 201, SCM 301, SCM 311, SCM 321, SCM 401, SCM 421, AC 201, EC 200, MG 201, STAT 282, FI 301, MG 401. International experience REQUIRED. STEM-eligible tracks available. Professional Experience required. Average time: 4 years.", "metadata": {"category": "program", "major": "Global Supply Chain Management", "level": "undergraduate"}},
    {"id": "req_fia_ug", "text": "Financial Information and Analysis BS degree requirements at Clarkson University (Reh School of Business). Total credits required: 120. Required: SB 113, AC 201, AC 202, AC 301, FI 201, FI 301, FI 311, FI 401, FI 411, EC 200, EC 301, MA 131, STAT 282. International experience required. CFA exam preparation strongly recommended. Professional Experience required.", "metadata": {"category": "program", "major": "Financial Information & Analysis", "level": "undergraduate"}},
    {"id": "req_bida_ug", "text": "Business Intelligence and Data Analytics BS degree requirements at Clarkson University (Reh School of Business). Total credits required: 120. Required: SB 113, AC 201, EC 200, CS 141, STAT 282, BA 201, BA 301, BA 311, BA 401, IS 301, MK 301, MG 401, FI 301. STEM-designated program. International experience required. Professional Experience required.", "metadata": {"category": "program", "major": "Business Intelligence & Data Analytics", "level": "undergraduate"}},
    {"id": "req_ba_analytics_ug", "text": "Business Analytics BS degree requirements at Clarkson University (Reh School of Business). STEM-designated program. Total credits required: 120. This is a new program launched in 2024. Required: SB 113, BA 201, BA 301, BA 311, BA 401, CS 141, STAT 282, AC 201, EC 200, IS 301, MG 401, FI 301. International experience required. Professional Experience required.", "metadata": {"category": "program", "major": "Business Analytics (STEM)", "level": "undergraduate"}},
    {"id": "req_ie_ug", "text": "Innovation and Entrepreneurship BS degree requirements at Clarkson University (Reh School of Business). Total credits required: 120. Required: SB 113, IE 201, IE 211, IE 301, IE 311, IE 401, IE 411, MG 201, MK 201, MK 301, FI 301, MG 401. International experience required. Strong connection to the Clarkson Ignite entrepreneurship program and the Cube business accelerator. Professional Experience required.", "metadata": {"category": "program", "major": "Innovation & Entrepreneurship", "level": "undergraduate"}},

    # ══════════════════════════════════════════════════════════
    #  GRADUATE DEGREE REQUIREMENTS
    # ══════════════════════════════════════════════════════════
    {"id": "req_cs_ms", "text": "MS in Computer Science requirements at Clarkson University. Total credits required: 30 graduate-level credits. Foundation course CS 541 (Computer Algorithms) is required and must be taken in the first semester. Students take 6 credits of programming-intensive courses and complete electives from groups: Group A (theory), Group B (systems), Group C (languages), Group D (AI/ML). Thesis option (research-based) or non-thesis option (professionally oriented) available. Both options available on-site and fully online. Full-time students typically complete in 2 semesters (1 year). Minimum 20 credits earned in residence at Clarkson. Admitted students had 100% placement rate in 2024.", "metadata": {"category": "program", "major": "Computer Science (MS)", "level": "graduate"}},
    {"id": "req_ds_ms", "text": "MS in Applied Data Science requirements at Clarkson University. Total credits required: 36. The program consists of 6 three-credit core graduate courses, 4 three-credit graduate electives, and 1 six-credit capstone course based on a sponsored project or internship. STEM-designated program. Full-time residential students complete in 3 semesters. Part-time students finish in about 2 years. Available at Potsdam campus or 100% online. Can be completed as a dual degree with the MBA (56 total credits).", "metadata": {"category": "program", "major": "Applied Data Science (MS) — STEM", "level": "graduate"}},
    {"id": "req_che_ms", "text": "MS in Chemical Engineering requirements at Clarkson University. Total credits required: 30 graduate-level credits, including at least 20 credits of course and seminar work. Required: 4 core ChE graduate courses, 2 additional technical graduate courses, 2 credits of seminar, and 10 credits of thesis research. Thesis must be orally defended before a committee of 3+ faculty. Typical completion: 4 semesters (2 years). A program is available for qualified BS chemists to earn the MS in 4 semesters.", "metadata": {"category": "program", "major": "Chemical Engineering (MS)", "level": "graduate"}},
    {"id": "req_ce_ms", "text": "MS in Civil and Environmental Engineering requirements at Clarkson University. Total credits required: 30, including at least 20 credits of course and seminar work. Specialty areas: environmental, geotechnical, structural, or water resources engineering. Thesis required with oral defense before 3+ faculty committee. Full-time students typically complete in 18-24 months (3-4 semesters). Available on campus in Potsdam or hybrid format. Full-time students may receive merit awards covering 4 credits per semester for 3 semesters.", "metadata": {"category": "program", "major": "Civil & Environmental Engineering (MS)", "level": "graduate"}},
    {"id": "req_me_ms", "text": "MS in Mechanical Engineering requirements at Clarkson University. Total credits required: 30 graduate-level credits including at least 20 hours of course and seminar work. Research or professional experience component required. Thesis or project option. Typical completion: 4 semesters. Research areas include fluid mechanics, thermodynamics, materials, robotics, and manufacturing.", "metadata": {"category": "program", "major": "Mechanical Engineering (MS)", "level": "graduate"}},
    {"id": "req_es_ms", "text": "MS in Environmental Science and Engineering requirements at Clarkson University. Total credits required: 30, including 2 credits of seminar and at least 6 credits of research (or 4 credits for project option). STEM-designated program. Students must take at least one Systems Thinking course and at least one Policy course. Thesis option: 3 additional electives (9 credits). Project option: 4 additional electives (12 credits). At least two electives must have environmental or sustainability focus.", "metadata": {"category": "program", "major": "Environmental Science & Engineering (MS)", "level": "graduate"}},
    {"id": "req_mba_residential", "text": "MBA Residential program requirements at Clarkson University (Reh School of Business). Total credits required: 35. The MBA consists of 15 courses. Can be completed in as little as 9 months, with 1-year, 18-month, and 2-year options also available. Classes held at Potsdam campus. A 3-credit experiential course (Global Business Strategies or international trip) is required. Students can use electives to earn an advanced certificate. Residential MBA Class of 2023 had 100% placement rate with starting salaries as high as $130K. Average starting salary for all MBA graduates: $76,300.", "metadata": {"category": "program", "major": "MBA — Residential (35 cr, 9 months–2 years)", "level": "graduate"}},
    {"id": "req_mba_online", "text": "Online MBA requirements at Clarkson University (Reh School of Business). Total credits required: 36. Consists of 10 core courses and 2 electives. Average completion time: approximately 1.5 years taking 2 classes per quarter. 100% online with no residency requirement. Students can start any term and attend full or part time. Up to 9 credit hours can be transferred with approval. Can earn advanced certificates by adding 2 courses. Ranked among top Online MBA programs by US News and World Report and Fortune.", "metadata": {"category": "program", "major": "MBA — Online (36 cr, ~1.5 years)", "level": "graduate"}},
    {"id": "req_mba_healthcare", "text": "MBA in Healthcare Management requirements at Clarkson University. Total credits required: 42, consisting of 14 courses (13 required + 1 elective). Can be completed in as little as 1 year full-time or 2-4 years part-time. Fully online. One of only nine programs in the US with dual AACSB and CAHME accreditation. 100% of students find a position in their field within 3 months of graduation, with salaries as high as $200K for Class of 2024. Internship requirement included. Students can combine with MS in Healthcare Data Analytics (19 courses total).", "metadata": {"category": "program", "major": "MBA — Healthcare Management (42 cr)", "level": "graduate"}},
    {"id": "req_mba_gscm", "text": "MBA in Global Supply Chain Management at Clarkson University (Reh School of Business). Total credits required: 35 (same structure as Residential MBA with SCM concentration). Includes 3-credit experiential international trip. Required courses cover: managerial economics, financial management, marketing strategy, operations and supply chain, organizational behavior, business analytics, and SCM-specific courses.", "metadata": {"category": "program", "major": "MBA — Global Supply Chain Management (35 cr)", "level": "graduate"}},
    {"id": "req_ot_ms", "text": "MS in Occupational Therapy requirements at Clarkson University. Total credits required: 92. Program duration: 24 months (6 semesters). Full-time, on-site program in Potsdam with up to 2 courses offered virtually. Includes Level I fieldwork in semesters 2 and 4, and Level II fieldwork in semesters 3 and 6. Accredited by ACOTE. Direct Entry option available for qualifying undergrads (guaranteed admission). Tuition: $11,035 per term. Contact: Otadmissions@clarkson.edu.", "metadata": {"category": "program", "major": "Occupational Therapy (MS, 92 cr, 6 semesters)", "level": "graduate"}},
    {"id": "req_dpt", "text": "Doctor of Physical Therapy (DPT) requirements at Clarkson University. Total credits required: 105. Program duration: 2 and 2/3 years (8 semesters). Full-time post-baccalaureate program. Includes 4 full-time clinical experiences plus hands-on integrated clinical experiences (ICE) throughout. Accredited by CAPTE. Direct Entry 4+3 program available for qualifying undergrads. Tuition: $12,719 per term flat rate. Applications via PTCAS. Contact: smarocco@clarkson.edu, pthealth@clarkson.edu, 315-268-7622.", "metadata": {"category": "program", "major": "Physical Therapy (DPT, 105 cr, 8 semesters)", "level": "graduate"}},
    {"id": "req_pa_ms", "text": "MS in Physician Assistant Studies requirements at Clarkson University. Program duration: 28 months (7 semesters). Full-time rigorous curriculum. Students participate in 9 clinical field experiences plus a 5-week elective for research. Concludes with a 1-month summative phase. Accredited by ARC-PA. Direct Entry program available for qualifying undergrads (guaranteed admission). Tuition: $13,685 per term. Applications must be submitted through CASPA. Direct entry contact: Lewis School of Health Sciences.", "metadata": {"category": "program", "major": "Physician Assistant Studies (MS, 28 months)", "level": "graduate"}},
    {"id": "req_phd", "text": "PhD programs at Clarkson University (Engineering and Sciences). Total credits required: minimum 90 credit hours from the BS level (or 60 beyond an MS). At least 36 credits of classroom coursework. Minimum 6 credits of research seminar. PhD candidacy procedure required within 2 years of full-time study. Original research thesis required and orally defended before a committee of at least 5 faculty members. Qualifying exam required within 1 year of admission. Up to 30 credit hours of MS transfer credit accepted. PhD programs available in: CS, Mechanical Engineering, Chemical Engineering, Civil & Environmental Engineering, Electrical & Computer Engineering, Physics, Mathematics, Materials Science & Engineering, Environmental Science & Engineering, Bioscience & Biotechnology.", "metadata": {"category": "program", "major": "PhD Programs", "level": "graduate"}},

    # ══════════════════════════════════════════════════════════
    #  ACADEMIC POLICIES
    # ══════════════════════════════════════════════════════════
    {"id": "pol_proexp", "text": "Professional Experience requirement at Clarkson University. ALL undergraduate students in ALL programs must complete at least one co-op, internship, or directed research project related to their professional goals before graduation. This is a graduation requirement, not optional. Students should register their professional experience through CS 499 (engineering/CS) or the equivalent course code for their major. The Parker Career Center (315-268-6477, career@clarkson.edu, ERC 2nd floor) helps students find co-ops and internships via Handshake.", "metadata": {"category": "policy", "topic": "graduation"}},
    {"id": "pol_intl_exp", "text": "International Experience requirement at Clarkson University Reh School of Business. ALL undergraduate students in the Reh School of Business must complete an international experience before graduation. This can be satisfied through: study abroad programs, international co-op/internship, or the international trip included in the MBA experiential course. The International Center (315-268-3943) supports international programs. Clarkson has partnerships with 55 universities in 28 countries.", "metadata": {"category": "policy", "topic": "graduation", "school": "business"}},
    {"id": "pol_gpa", "text": "GPA requirements at Clarkson University. Minimum cumulative GPA of 2.0 required for undergraduate graduation. Graduate students must maintain a minimum 3.0 GPA. Academic probation occurs when GPA falls below 2.0 (undergraduate) or 3.0 (graduate). Students on academic probation should immediately contact Student Achievement Services (TAC 207, 315-268-6451) and the Student Success Center (ERC 1400, 315-268-2209) for academic coaching support.", "metadata": {"category": "policy", "topic": "academic_standing"}},
    {"id": "pol_transfer", "text": "Transfer credit policy at Clarkson University. Undergraduate students may transfer credits from accredited institutions. Transfer credits must be evaluated by the Registrar's Office. Maximum transfer credits accepted varies by program. Graduate students: up to 30 credit hours of transfer credit accepted for PhD programs; up to 9 credit hours for MBA online; up to 6 credit hours for MBA Healthcare. Contact Student Achievement Services (TAC 207, 315-268-6451) for transfer credit evaluation.", "metadata": {"category": "policy", "topic": "transfer"}},
    {"id": "pol_4plus1", "text": "4+1 programs at Clarkson University allow qualified undergraduate students to earn a master's degree in 5 total years. Students take 2 graduate courses during their senior year that count toward the master's degree. Programs available: any BS to MBA; BS in Biology or Biomolecular Science to MS in Bioscience and Biotechnology; and other combinations. Students should apply during their junior year (5th or 6th semester). Associated Colleges students (SUNY Canton, SUNY Potsdam, St. Lawrence University) can also participate via cross-registration.", "metadata": {"category": "policy", "topic": "accelerated_programs"}},
    {"id": "pol_registration", "text": "Course registration at Clarkson University. Students register for courses through the myCU student portal. Registration windows open based on credit hours completed — seniors register first, then juniors, sophomores, freshmen. Graduate students register through the graduate portal. Degree audit and course planning support available at Student Achievement Services (TAC 207, 315-268-6451). Add/drop period: typically the first 2 weeks of each semester. Late withdrawal with W grade: typically through week 10. Contact SAS for exact current-semester deadlines.", "metadata": {"category": "policy", "topic": "registration"}},
    {"id": "pol_academic_calendar", "text": "Clarkson University academic calendar. Fall semester: typically late August through mid-December. Spring semester: typically mid-January through early May. Summer sessions available (shorter, compressed). MBA Residential program starts in August and ends in May. Graduate programs follow the same academic calendar. Key dates vary by year — always check the official academic calendar at clarkson.edu/admissions-financial-aid/sas/academic-calendar or contact SAS at TAC 207, 315-268-6451.", "metadata": {"category": "policy", "topic": "calendar"}},

    # ══════════════════════════════════════════════════════════
    #  CAMPUS RESOURCES
    # ══════════════════════════════════════════════════════════
    {"id": "res_ssc", "text": "Student Success Center (SSC) at Clarkson University. Location: ERC 1400. Phone: 315-268-2209. Email: ssc@clarkson.edu. Hours: Monday through Friday, 8am to 4:30pm. Services: free one-on-one tutoring (sign up via myCU), academic skills coaching, time management, study strategies, test preparation, and learning accommodations referrals. Also home to HEOP (Higher Education Opportunity Program) and CUPO (Clarkson University Pre-College Opportunity) programs supporting underrepresented students. Over 30% of Clarkson students use SSC services each year.", "metadata": {"category": "resource", "type": "academic_support"}},
    {"id": "res_writing", "text": "Writing Center at Clarkson University. Location: Snell Hall 139. Phone: 315-268-4439. Email: wcenter@clarkson.edu. Hours: Monday through Friday, by appointment. Services: free 25-minute one-on-one sessions with trained peer writing tutors. Reviews all types of writing including essays, lab reports, technical documents, business plans, thesis chapters, and graduate school application essays. Students should bring their assignment instructions. Online resources also available via the Writing Center website.", "metadata": {"category": "resource", "type": "academic_support"}},
    {"id": "res_career", "text": "Kevin and Annie Parker Career Center at Clarkson University. Location: ERC 2nd Floor. Phone: 315-268-6477. Email: career@clarkson.edu. Hours: Monday through Friday, 8am to 4:30pm. Services: resume and cover letter reviews, mock interviews, career counseling, co-op and internship search via Handshake platform (750,000+ companies), job postings, and employer connections. Career Fairs held twice yearly (fall and spring) with 200+ employers attending including Amazon, IBM, GE, Lockheed Martin, Pfizer, Deloitte, and many more. All undergraduate students must complete a Professional Experience before graduation. Graduate students also welcome.", "metadata": {"category": "resource", "type": "career"}},
    {"id": "res_shac", "text": "Student Health and Counseling (SHAC) at Clarkson University. Location: ERC Suite 1300. Phone: 315-268-6633. Email: shac@clarkson.edu. Hours: Monday through Friday, 8am to 4:30pm. Services: on-campus health clinic for illness and injury, immunizations, individual and group counseling, psychiatric services, and mental health crisis support. 24/7 crisis support available through Campus Safety at 315-268-6666. Also partnered with Mantra Health for FREE online therapy, wellness coaching, and on-demand mental health support for ALL enrolled students. Over 50% of Clarkson students use health and counseling services annually.", "metadata": {"category": "resource", "type": "health"}},
    {"id": "res_sas", "text": "Student Achievement Services (SAS) at Clarkson University. Location: TAC 207. Phone: 315-268-6451. Email: sas@clarkson.edu. Hours: Monday through Friday, 8am to 4:30pm. Services: one-stop office combining the Registrar, academic advising, Bursar, and Financial Aid. Handles: FAFSA guidance, student loans, tuition payment plans, emergency financial assistance, transcript requests, academic records, course scheduling, graduation audits, degree audits, and academic calendar inquiries. For graduate students, contact Graduate Admissions at 518-631-9831 or graduate@clarkson.edu.", "metadata": {"category": "resource", "type": "administrative"}},
    {"id": "res_accessibility", "text": "Office of Accessibility Services at Clarkson University. Phone: 315-268-2006. Email: accessibility@clarkson.edu. Hours: Monday through Friday, 8am to 4:30pm. Services: academic accommodations for students with disabilities including learning disabilities (ADHD, dyslexia), mental health conditions, physical disabilities, and chronic illnesses. Provides: extended test time, note-taking support, assistive technology, alternative format materials, and other academic adjustments. Students must register with the office and provide documentation to receive accommodations.", "metadata": {"category": "resource", "type": "accessibility"}},
    {"id": "res_international", "text": "International Center at Clarkson University. Location: Potsdam campus. Phone: 315-268-3943. Hours: Monday through Friday, 8am to 4:30pm. Services: visa and immigration support (F-1, J-1 status), STEM OPT application assistance, CPT authorization, I-20 management, cultural adjustment support, and study abroad program coordination. Clarkson has partnerships with 55 universities in 28 countries for study abroad. International experience is required for all Reh School of Business undergraduate students.", "metadata": {"category": "resource", "type": "international"}},
    {"id": "res_crisis", "text": "Mental health crisis resources at Clarkson University. On-campus: Campus Safety 24/7 at 315-268-6666. SHAC counseling (non-emergency): 315-268-6633, ERC Suite 1300. Regional: Reach Out Hotline 24/7 at 315-265-2422 (reachouthotline.org) — provides crisis counseling, mobile crisis team, and resource referrals. National: 988 Suicide and Crisis Lifeline — call or text 988, available 24/7, free and confidential. Mantra Health: free online therapy for all enrolled Clarkson students. If in immediate danger, call 911.", "metadata": {"category": "resource", "type": "crisis"}},
    {"id": "res_financial_aid", "text": "Financial Aid at Clarkson University. Office: Student Achievement Services, TAC 207, 315-268-6451. Types of aid available: merit scholarships (automatically considered at admission), need-based grants, federal student loans (Stafford, PLUS), work-study programs, graduate assistantships (provide tuition reduction in exchange for 10-20 hours of departmental work per week), and emergency financial assistance. Graduate students: most engineering and science PhD programs offer full funding through research or teaching assistantships. MBA and professional programs: merit-based scholarships available. FAFSA must be completed annually for need-based aid.", "metadata": {"category": "resource", "type": "financial"}},

    # ══════════════════════════════════════════════════════════
    #  CAREER INFORMATION
    # ══════════════════════════════════════════════════════════
    {"id": "career_outcomes", "text": "Clarkson University career outcomes and placement statistics. Class of 2023 undergraduate placement rate: 99%. Average starting salary for Class of 2023 undergraduates: $71,000+. Class of 2024 Mechanical Engineering average starting salary: $74,814 with 98% placement. Class of 2024 Electrical Engineering: 100% placement rate. Chemical Engineering average starting salary: over $74,000. MBA graduate placement rate: 97-100%. Average MBA starting salary: $76,300. MBA Healthcare Management: 100% placement within 3 months, salaries up to $200K for Class of 2024.", "metadata": {"category": "career", "topic": "outcomes"}},
    {"id": "career_employers", "text": "Top employers recruiting at Clarkson University. Engineering: GE Aviation, GE Vernova, NASA, Tesla, SpaceX, Lockheed Martin, Raytheon, Boeing, Amphenol, Corning, IBM, Amazon, Northrop Grumman, US Army Corps of Engineers, NYS DOT, HDR, AECOM. Business and analytics: Amazon, Deloitte, PwC, Goldman Sachs, JPMorgan Chase, Walmart, Raytheon. Life sciences: Pfizer, Albany Medical Center, BASF, Air Products. Government and environment: NYSERDA, EPA, NYS DEC. Career Fairs in fall and spring bring 200+ employers to campus. Students also access 750,000+ companies via Handshake.", "metadata": {"category": "career", "topic": "employers"}},
    {"id": "career_handshake", "text": "Handshake at Clarkson University. The primary platform for job and internship searching. All Clarkson students have access to Handshake which connects to 750,000+ companies and millions of job postings. Students should create a complete profile with resume, major, GPA, and career interests. Career Fair companies recruit directly through Handshake. The Parker Career Center (ERC 2nd floor, 315-268-6477) provides Handshake training and resume reviews to optimize student profiles. Graduate students can also use Handshake.", "metadata": {"category": "career", "topic": "job_search"}},
    {"id": "career_coop", "text": "Co-op and internship program at Clarkson University. Co-ops are typically full-time, paid positions lasting 1-2 semesters, often with academic credit. Internships are usually 10-12 week summer positions. Both satisfy the Professional Experience graduation requirement. Students should start searching at least 6-9 months in advance. The Parker Career Center (ERC 2nd floor, 315-268-6477, career@clarkson.edu) hosts Career Fairs each fall and spring semester with 200+ employers. Students register their professional experience through their major department.", "metadata": {"category": "career", "topic": "experience"}},
    {"id": "career_ignite", "text": "Clarkson Ignite entrepreneurship program and Cube business accelerator. Clarkson Ignite supports student entrepreneurs through the Ignite Presidential Fellows program, business plan competitions, and entrepreneurship courses. The Cube Accelerator provides mentorship, resources, and sometimes seed funding for student startups. Innovation and Entrepreneurship majors have direct access to these programs. All Clarkson students can participate. Contact the Reh School of Business or visit the Ignite program for details.", "metadata": {"category": "career", "topic": "entrepreneurship"}},
]
